# @package _global_

# config for Hyperparameter Optimization with Optuna
# python src/train.py -m +hpo=optuna
# python src/train.py -m +hpo=optuna hydra.sweeper.n_trials=25

defaults:
  - override /hydra/sweeper: optuna

hydra:
  sweeper:
    sampler:
      _target_: optuna.samplers.TPESampler
      seed: 42
    direction: maximize
    n_trials: 20
    params:
      params.lr: interval(0.0001, 0.01)
      params.batch_size: choice(64, 128)
      params.weight_decay: interval(0.00001, 0.001)