# @package _global_

# config for Hyperparameter Optimization with Optuna
# python src/train.py -m +hpo=optuna
# python src/train.py -m +hpo=optuna hydra.sweeper.n_trials=25

defaults:
  - override /hydra/sweeper: optuna

hydra:
  sweeper:
    sampler:
      _target_: optuna.samplers.TPESampler
      seed: 42
    direction: maximize
    n_trials: 25
    params:
      params.mosaic: choice(0.0, 0.5, 1.0)
      params.epochs: 200
      params.degrees: choice(0.0, 10.0, 20.0, 50.0, 70.0, 90.0)
      params.batch_size: 32
      params.lr: 0.001
      params.lrf: 0.1
      params.protocol: t1
      params.experiment_name: optuna4
      