#Base Settings
defaults:
  - _self_
  - files: polyp
params:
  protocol: t1
  seed: 42
  val_ratio: 0.2
  # Diff threshold for considering two consecutive frames as near-duplicates (0.0 to 1.0, representing percentage of pixel difference).
  duplicate_threshold: 0.05
  # If true, regenerates cached intermediates (e.g., SUN flat images/labels) even if they already exist.
  force_rebuild_cache: false
  # Route to the custom model YOLO yaml file or the name of a ultralystics model yaml.
  #model: models/yolov5TST.yaml
  model: null
  pretrained_weights: yolov5su.pt
  img_size: 640
  epochs: 300
  experiment_name: Polyp_Detection
  batch_size: 128
  lr: 0.01
  weight_decay: 0.0005
  optimizer: AdamW
  device: [0, 1]
  
  